name: smoelenboek tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - name: run smoelenboek tests
        uses: cypress-io/github-action@v2
        with:
          start: "npm run dev"
          wait-on: "http://localhost:5000"
          config: baseUrl=http://localhost:5000